/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/japan.glb
*/


import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import  gsap from 'gsap';

export const FLOOR_HEIGHT = 2.3;
export const NB_FLOORS = 3;

export function Japan (props) {
  const { nodes, materials} = useGLTF('./models/japan.glb')
  const ref = useRef();
  const tl = useRef ();
  const libraryRef = useRef();
  const atticRef = useRef();

  const scroll = useScroll ();

  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    tl.current = gsap.timeline();

    // VERTICAL ANIMATION
    tl.current.to(
      ref.current.position,
      {
        duration: 2,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
      },
      0
    );

    // FLOOR ROTATION
    tl.current.to(
      ref.current.rotation,
      {duration: 1, x: 0, y: Math.PI / 6, z: 0},
      0
    );

    tl.current.to(
      ref.current.rotation,
      {duration: 1, x: 0, y: -Math.PI / 6, z: 0},
      0
    )

    // FLOOR MOVEMENT
    tl.current.to(
      ref.current.position,
      {
        duration: 1,
        x: -1,
        z: 2,
      },
      0
    );
    tl.current.to(
      ref.current.position,
      {
        duration: 1,
        x: 1,
        z: 2,
      },
      1
    );

    // LIBRARY FLOOR
    {/*tl.current.from(
      libraryRef.current.position,
      {
        duration: 0.5,
        x: -2,
      },
      0.5
    );
    tl.current.from(
      libraryRef.current.rotation,
      {
        duration: 0.5,
        y: -Math.PI / 2,
      },
      0
    ); */}

    // ATTIC
    tl.current.from(
      atticRef.current.position,
      {
        duration: 1.5,
        y: 2,
      },
      0
    );

    tl.current.from(
      atticRef.current.rotation,
      {
        duration: 0.5,
        y: Math.PI / 2,
      },
      1
    );

    tl.current.from(
      atticRef.current.position,
      {
        duration: 0.5,

        z: -2,
      },
      1.5
    );
  }, []);



  return (
    <group 
      ref={ref} 
      {...props} 
      dispose={null}
      position={[0.5, 0, 0]}
      rotation={[0, -Math.PI / 3, 0]}
    >


        <group position={[-5.864, 13.578, -4.918]} rotation={[0, -0.141, 0]} scale={0.432}>
          <group ref={atticRef}>      
            <group name="floor3">
          <mesh name="Plane049" geometry={nodes.Plane049.geometry} material={materials['Material.072']} />
          <mesh name="Plane049_1" geometry={nodes.Plane049_1.geometry} material={materials['Material.070']} />
          <mesh name="Plane049_2" geometry={nodes.Plane049_2.geometry} material={materials['Material.075']} />
          <mesh name="Plane049_3" geometry={nodes.Plane049_3.geometry} material={materials['Material.076']} />
          <mesh name="Plane049_4" geometry={nodes.Plane049_4.geometry} material={materials['Material.077']} />
          <mesh name="Plane049_5" geometry={nodes.Plane049_5.geometry} material={materials['Material.081']} />
          <mesh name="Plane049_6" geometry={nodes.Plane049_6.geometry} material={materials['Material.083']} />
          <mesh name="Plane049_7" geometry={nodes.Plane049_7.geometry} material={materials['Material.084']} />
          <mesh name="Plane049_8" geometry={nodes.Plane049_8.geometry} material={materials['Material.085']} />
          <mesh name="Plane049_9" geometry={nodes.Plane049_9.geometry} material={materials['Material.086']} />
          <mesh name="Plane049_10" geometry={nodes.Plane049_10.geometry} material={materials['Material.087']} />
          <mesh name="Plane049_11" geometry={nodes.Plane049_11.geometry} material={materials['//Material.001']} />
          <mesh name="Plane049_12" geometry={nodes.Plane049_12.geometry} material={materials['Material.045']} />
          <mesh name="Plane049_13" geometry={nodes.Plane049_13.geometry} material={materials['Material.088']} />
          <mesh name="Plane049_14" geometry={nodes.Plane049_14.geometry} material={materials['Material.089']} />
          <mesh name="Plane049_15" geometry={nodes.Plane049_15.geometry} material={materials['Material.090']} />
          <mesh name="Plane049_16" geometry={nodes.Plane049_16.geometry} material={materials['Material.091']} />
          <mesh name="Plane049_17" geometry={nodes.Plane049_17.geometry} material={materials['Material.092']} />
          <mesh name="Plane049_18" geometry={nodes.Plane049_18.geometry} material={materials['Material.079']} />
          <mesh name="Plane049_19" geometry={nodes.Plane049_19.geometry} material={materials['Material.003']} />
          <mesh name="Plane049_20" geometry={nodes.Plane049_20.geometry} material={materials.phong31} />
          <mesh name="Plane049_21" geometry={nodes.Plane049_21.geometry} material={materials.phong10} />
          <mesh name="Plane049_22" geometry={nodes.Plane049_22.geometry} material={materials['Material.048']} />
          <mesh name="Plane049_23" geometry={nodes.Plane049_23.geometry} material={materials.lambert1} />
          <mesh name="Plane049_24" geometry={nodes.Plane049_24.geometry} material={materials.phong19} />
          <mesh name="Plane049_25" geometry={nodes.Plane049_25.geometry} material={materials.phong53} />
          <mesh name="Plane049_26" geometry={nodes.Plane049_26.geometry} material={materials.phong54} />
          <mesh name="Plane049_27" geometry={nodes.Plane049_27.geometry} material={materials['Material.036']} />
          <mesh name="Plane049_28" geometry={nodes.Plane049_28.geometry} material={materials['Material.053']} />
          <mesh name="Plane049_29" geometry={nodes.Plane049_29.geometry} material={materials['Material.040']} />
          <mesh name="Plane049_30" geometry={nodes.Plane049_30.geometry} material={materials.phong57} />
          <mesh name="Plane049_31" geometry={nodes.Plane049_31.geometry} material={materials.phong55} />
          <mesh name="Plane049_32" geometry={nodes.Plane049_32.geometry} material={materials.phong1} />
          <mesh name="Plane049_33" geometry={nodes.Plane049_33.geometry} material={materials.phong40} />
          <mesh name="Plane049_34" geometry={nodes.Plane049_34.geometry} material={materials.phong5} />
          <mesh name="Plane049_35" geometry={nodes.Plane049_35.geometry} material={materials['Material.043']} />
          <mesh name="Plane049_36" geometry={nodes.Plane049_36.geometry} material={materials.phong2} />
          <mesh name="Plane049_37" geometry={nodes.Plane049_37.geometry} material={materials.phong6} />
          <mesh name="Plane049_38" geometry={nodes.Plane049_38.geometry} material={materials.phong43} />
          <mesh name="Plane049_39" geometry={nodes.Plane049_39.geometry} material={materials.phong7} />
          <mesh name="Plane049_40" geometry={nodes.Plane049_40.geometry} material={materials.phong25} />
          <mesh name="Plane049_41" geometry={nodes.Plane049_41.geometry} material={materials.phong26} />
          <mesh name="Plane049_42" geometry={nodes.Plane049_42.geometry} material={materials.phong42} />
          <mesh name="Plane049_43" geometry={nodes.Plane049_43.geometry} material={materials.phong41} />
          <mesh name="Plane049_44" geometry={nodes.Plane049_44.geometry} material={materials['Material.047']} />
            </group>
          </group>
        </group>

      </group>
  )
}

useGLTF.preload('./models/japan.glb')
