/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/japanese_house.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Japanese_house(props) {
  const { nodes, materials } = useGLTF('./models/japanese_house.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -3, 4.294]} scale={0.732}>
        <mesh geometry={nodes.Plane049.geometry} material={materials['Material.072']} />
        <mesh geometry={nodes.Plane049_1.geometry} material={materials['Material.070']} />
        <mesh geometry={nodes.Plane049_2.geometry} material={materials['Material.075']} />
        <mesh geometry={nodes.Plane049_3.geometry} material={materials['Material.076']} />
        <mesh geometry={nodes.Plane049_4.geometry} material={materials['Material.077']} />
        <mesh geometry={nodes.Plane049_5.geometry} material={materials['Material.081']} />
        <mesh geometry={nodes.Plane049_6.geometry} material={materials['Material.083']} />
        <mesh geometry={nodes.Plane049_7.geometry} material={materials['Material.084']} />
        <mesh geometry={nodes.Plane049_8.geometry} material={materials['Material.085']} />
        <mesh geometry={nodes.Plane049_9.geometry} material={materials['Material.086']} />
        <mesh geometry={nodes.Plane049_10.geometry} material={materials['Material.087']} />
        <mesh geometry={nodes.Plane049_11.geometry} material={materials['//Material.001']} />
        <mesh geometry={nodes.Plane049_12.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Plane049_13.geometry} material={materials['Material.088']} />
        <mesh geometry={nodes.Plane049_14.geometry} material={materials['Material.089']} />
        <mesh geometry={nodes.Plane049_15.geometry} material={materials['Material.090']} />
        <mesh geometry={nodes.Plane049_16.geometry} material={materials['Material.091']} />
        <mesh geometry={nodes.Plane049_17.geometry} material={materials['Material.092']} />
        <mesh geometry={nodes.Plane049_18.geometry} material={materials['Material.079']} />
        <mesh geometry={nodes.Plane049_19.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane049_20.geometry} material={materials.phong31} />
        <mesh geometry={nodes.Plane049_21.geometry} material={materials.phong10} />
        <mesh geometry={nodes.Plane049_22.geometry} material={materials['Material.048']} />
        <mesh geometry={nodes.Plane049_23.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.Plane049_24.geometry} material={materials.phong19} />
        <mesh geometry={nodes.Plane049_25.geometry} material={materials.phong53} />
        <mesh geometry={nodes.Plane049_26.geometry} material={materials.phong54} />
        <mesh geometry={nodes.Plane049_27.geometry} material={materials['Material.036']} />
        <mesh geometry={nodes.Plane049_28.geometry} material={materials['Material.053']} />
        <mesh geometry={nodes.Plane049_29.geometry} material={materials['Material.040']} />
        <mesh geometry={nodes.Plane049_30.geometry} material={materials.phong57} />
        <mesh geometry={nodes.Plane049_31.geometry} material={materials.phong55} />
        <mesh geometry={nodes.Plane049_32.geometry} material={materials.phong1} />
        <mesh geometry={nodes.Plane049_33.geometry} material={materials.phong40} />
        <mesh geometry={nodes.Plane049_34.geometry} material={materials.phong5} />
        <mesh geometry={nodes.Plane049_35.geometry} material={materials['Material.043']} />
        <mesh geometry={nodes.Plane049_36.geometry} material={materials.phong2} />
        <mesh geometry={nodes.Plane049_37.geometry} material={materials.phong6} />
        <mesh geometry={nodes.Plane049_38.geometry} material={materials.phong43} />
        <mesh geometry={nodes.Plane049_39.geometry} material={materials.phong7} />
        <mesh geometry={nodes.Plane049_40.geometry} material={materials.phong25} />
        <mesh geometry={nodes.Plane049_41.geometry} material={materials.phong26} />
        <mesh geometry={nodes.Plane049_42.geometry} material={materials.phong42} />
        <mesh geometry={nodes.Plane049_43.geometry} material={materials.phong41} />
        <mesh geometry={nodes.Plane049_44.geometry} material={materials['Material.047']} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/japanese_house.glb')
